import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'motion/react';
import { Settings, Lock, ShoppingCart, Copy, Star, MessageSquare, ChevronRight, HelpCircle } from 'lucide-react';
import { ScotiaLogoSVG } from '../components/ScotiaIcons';
const MoreView = ({ onSignOut, onAction }) => {
    const menuItems = [
        { label: 'Profile and settings', icon: _jsx(Settings, { size: 22, className: "text-[#6B7280]" }), action: 'profile_settings' },
        { label: 'Privacy and security', icon: _jsx(Lock, { size: 22, className: "text-[#0ea5e9]" }), action: 'security_privacy', isNew: true },
        { label: 'Products and services', icon: _jsx(ShoppingCart, { size: 22, className: "text-[#db2777]" }), action: 'products_services' },
        { label: 'Saved applications', icon: _jsx(Copy, { size: 22, className: "text-[#0284c7]" }), action: 'saved_applications' },
        { label: 'Get to know the app', icon: _jsx(Star, { size: 22, className: "text-[#eab308]" }), action: 'get_to_know' },
        { label: 'Contact us', icon: _jsx(MessageSquare, { size: 22, className: "text-[#334155]" }), action: 'contact_us' },
    ];
    return (_jsxs(motion.div, { initial: { opacity: 0 }, animate: { opacity: 1 }, exit: { opacity: 0 }, className: "absolute inset-0 z-[100] flex flex-col font-sans bg-white text-[#1A1A1A]", children: [_jsxs("div", { className: "pt-12 pb-4 px-6 flex items-center justify-between shrink-0 bg-white shadow-[0_2px_10px_rgba(0,0,0,0.05)] z-10", children: [_jsx(ScotiaLogoSVG, { color: "#ED0711", className: "w-8 h-8" }), _jsx("h1", { className: "text-[16px] font-bold tracking-tight text-gray-900", children: "More" }), _jsx("button", { className: "p-1", children: _jsx(HelpCircle, { size: 24, className: "text-gray-900" }) })] }), _jsxs("div", { className: "flex-1 overflow-y-auto no-scrollbar flex flex-col", children: [_jsx("div", { className: "bg-white mt-6", children: menuItems.map((item, idx) => (_jsxs("button", { onClick: () => onAction(item.action), className: "w-full flex items-center px-8 py-4 bg-white active:bg-gray-50 transition-colors", children: [_jsx("div", { className: "w-10 flex justify-start", children: item.icon }), _jsx("span", { className: "flex-1 text-left text-[16px] text-[#333333]", children: item.label }), item.isNew && (_jsx("span", { className: "mr-4 bg-[#C2185B] text-white text-[11px] font-bold px-2 py-1 rounded-md", children: "NEW" })), _jsx(ChevronRight, { size: 20, className: "text-[#9333ea]" })] }, idx))) }), _jsx("div", { className: "px-8 mt-6", children: _jsx("button", { onClick: onSignOut, className: "w-full py-3.5 rounded-lg border border-[#ED0711] text-[#ED0711] font-bold text-[16px] flex items-center justify-center active:bg-[#ED0711]/10 transition-colors", children: "Sign out" }) }), _jsxs("div", { className: "px-8 mt-auto mb-24 pt-12", children: [_jsxs("p", { className: "text-[16px] text-gray-500 mb-1", children: [_jsx("span", { className: "font-bold text-gray-600", children: "Model:" }), " iphone 8"] }), _jsxs("p", { className: "text-[16px] text-gray-500 mb-1", children: [_jsx("span", { className: "font-bold text-gray-600", children: "OS Version:" }), " 10"] }), _jsxs("p", { className: "text-[16px] text-gray-500", children: [_jsx("span", { className: "font-bold text-gray-600", children: "App Version:" }), " 20.9.2"] })] })] })] }));
};
export default MoreView;
