import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Apple, Search, Wifi, Battery, Folder, Globe, Mail, Music, Settings, Trash2 } from 'lucide-react';
export default function MacOSLayout() {
    return (_jsxs("div", { className: "flex-1 h-full w-full bg-[#1c1c1e] bg-cover bg-center relative overflow-hidden", style: { backgroundImage: 'url(https://picsum.photos/seed/macos/1920/1080)' }, children: [_jsxs("div", { className: "absolute top-0 left-0 right-0 h-8 bg-black/20 backdrop-blur-md border-b border-white/10 flex items-center justify-between px-4 z-50", children: [_jsxs("div", { className: "flex items-center gap-4 text-xs font-medium text-white", children: [_jsx(Apple, { className: "w-4 h-4" }), _jsx("span", { className: "font-bold", children: "Finder" }), _jsx("span", { children: "File" }), _jsx("span", { children: "Edit" }), _jsx("span", { children: "View" }), _jsx("span", { children: "Go" }), _jsx("span", { children: "Window" }), _jsx("span", { children: "Help" })] }), _jsxs("div", { className: "flex items-center gap-4 text-xs font-medium text-white", children: [_jsx(Wifi, { className: "w-4 h-4" }), _jsx(Battery, { className: "w-4 h-4" }), _jsx(Search, { className: "w-4 h-4" }), _jsx("div", { className: "flex flex-col items-end", children: _jsx("span", { children: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }) })] })] }), _jsxs("div", { className: "absolute bottom-4 left-1/2 -translate-x-1/2 h-16 bg-white/20 backdrop-blur-xl border border-white/20 rounded-2xl flex items-center gap-2 px-2 z-50", children: [_jsx(DockIcon, { icon: _jsx(Folder, { className: "text-blue-400" }), label: "Finder" }), _jsx(DockIcon, { icon: _jsx(Globe, { className: "text-blue-500" }), label: "Safari" }), _jsx(DockIcon, { icon: _jsx(Mail, { className: "text-blue-600" }), label: "Mail" }), _jsx(DockIcon, { icon: _jsx(Music, { className: "text-pink-500" }), label: "Music" }), _jsx(DockIcon, { icon: _jsx(Settings, { className: "text-gray-400" }), label: "Settings" }), _jsx("div", { className: "w-[1px] h-10 bg-white/20 mx-1" }), _jsx(DockIcon, { icon: _jsx(Trash2, { className: "text-gray-300" }), label: "Trash" })] }), _jsxs("div", { className: "absolute top-12 right-4 flex flex-col gap-8", children: [_jsx(DesktopIcon, { icon: _jsx(Folder, { className: "text-blue-400" }), label: "Macintosh HD" }), _jsx(DesktopIcon, { icon: _jsx(Folder, { className: "text-blue-400" }), label: "Documents" })] })] }));
}
function DockIcon({ icon, label }) {
    return (_jsxs("div", { className: "relative group", children: [_jsx("div", { className: "w-12 h-12 flex items-center justify-center hover:scale-125 transition-transform cursor-pointer origin-bottom", children: icon }), _jsx("div", { className: "absolute -top-10 left-1/2 -translate-x-1/2 bg-black/80 backdrop-blur-md text-white text-[10px] px-2 py-1 rounded opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap", children: label })] }));
}
function DesktopIcon({ icon, label }) {
    return (_jsxs("div", { className: "flex flex-col items-center gap-1 p-2 hover:bg-white/10 rounded cursor-pointer group", children: [_jsx("div", { className: "w-12 h-12 flex items-center justify-center group-hover:scale-110 transition-transform", children: icon }), _jsx("span", { className: "text-[10px] text-white text-center font-medium drop-shadow-md", children: label })] }));
}
